package me.voidxwalker.serversiderng.mixin;

import me.voidxwalker.serversiderng.RNGHandler;
import me.voidxwalker.serversiderng.ServerSideRng;
import net.minecraft.entity.boss.dragon.EnderDragonFight;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.ModifyArg;

@Mixin(EnderDragonFight.class)
public class EnderDragonFightMixin {
    /**
     * Uses the from {@link RNGHandler#getRngValue(RNGHandler.RNGTypes)} obtained random {@code Long}, that has been generated by the verification server, for the {@link RNGHandler.RNGTypes#ENDER_DRAGON_ROTATION}.
     * @author Void_X_Walker
     */
    @ModifyArg(method = "createDragon", at = @At(value = "INVOKE", target = "Lnet/minecraft/entity/boss/dragon/EnderDragonEntity;refreshPositionAndAngles(DDDFF)V"),index = 3)
    private float modifyDragonAngle(float originalRotation) {
        if (ServerSideRng.inSpeedrun()) {
            return ServerSideRng.currentSpeedrun.getCurrentRNGHandler().getRngValue(RNGHandler.RNGTypes.ENDER_DRAGON_ROTATION) % 360;
        }
        else {
            return originalRotation;
        }
    }
}
