package me.voidxwalker.serversiderng.mixin.rng_verification;

import me.voidxwalker.serversiderng.RNGHandler;
import me.voidxwalker.serversiderng.RNGSession;
import net.minecraft.entity.boss.dragon.EnderDragonFight;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.ModifyArg;

import java.util.function.Supplier;

@Mixin(EnderDragonFight.class)
public class EnderDragonFightMixin {
    /**
     * Uses the from {@link RNGSession#getRngContext(RNGHandler.RNGTypes)} obtained random {@code Long}, that has been generated by the {@code Verification-Server}, for the {@link RNGHandler.RNGTypes#ENDER_DRAGON_ROTATION}.
     * @see  RNGSession#getRngContext(RNGHandler.RNGTypes)
     * @author Void_X_Walker
     */
    @ModifyArg(
            method = "createDragon",
            at = @At(value = "INVOKE",
            target = "Lnet/minecraft/entity/boss/dragon/EnderDragonEntity;refreshPositionAndAngles(DDDFF)V"),
            index = 3
    )
    private float modifyDragonAngle(float originalRotation) {
        return RNGSession.getRngContext(RNGHandler.RNGTypes.ENDER_DRAGON_ROTATION)
            .map(Supplier::get)
            .map((it) -> (float) it % 360)
            .orElse(originalRotation);
    }
}
