package me.voidxwalker.serversiderng.mixin.rng_verification;

import me.voidxwalker.serversiderng.RNGHandler;
import me.voidxwalker.serversiderng.RNGSession;
import net.minecraft.entity.boss.dragon.EnderDragonFight;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.ModifyArg;

@Mixin(EnderDragonFight.class)
public class EnderDragonFightMixin {
    /**
     * Uses the from {@link RNGHandler#getRngValue(RNGHandler.RNGTypes)} obtained random {@code Long}, that has been generated by the {@code Verification-Server}, for the {@link RNGHandler.RNGTypes#ENDER_DRAGON_ROTATION}.
     * @see RNGHandler#getRngValue(RNGHandler.RNGTypes)
     * @author Void_X_Walker
     */
    @ModifyArg(
            method = "createDragon",
            at = @At(value = "INVOKE",
            target = "Lnet/minecraft/entity/boss/dragon/EnderDragonEntity;refreshPositionAndAngles(DDDFF)V"),
            index = 3
    )
    private float modifyDragonAngle(float originalRotation) {
        if (RNGSession.inSession()) {
            return RNGSession.getInstance().getCurrentRNGHandler().getRngValue(RNGHandler.RNGTypes.ENDER_DRAGON_ROTATION) % 360;
        }
        return originalRotation;
    }
}
