package me.voidxwalker.serversiderng.mixin.rng_verification;

import me.voidxwalker.serversiderng.RNGHandler;
import me.voidxwalker.serversiderng.ServerSideRNG;
import net.minecraft.entity.mob.PiglinBrain;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.ModifyArg;

import java.util.Random;
import java.util.function.Supplier;

@Mixin(PiglinBrain.class)
public class PiglinBrainMixin {
    /**
     * Uses the from {@link  ServerSideRNG#getRngContext(RNGHandler.RNGTypes)} obtained random {@code Long}, that has been generated by the {@code Verification-Server}, as a seed for the {@link RNGHandler.RNGTypes#BARTER} RNG.
     * @return A {@code Random} generated with a seed obtained by the verification or the vanilla {@code Random} if {@code ServerSideRNG} is not in a session
     * @see  ServerSideRNG#getRngContext(RNGHandler.RNGTypes)
     * @author Void_X_Walker
     */
    @ModifyArg(method = "getBarteredItem",at = @At(value = "INVOKE",target = "Lnet/minecraft/loot/context/LootContext$Builder;random(Ljava/util/Random;)Lnet/minecraft/loot/context/LootContext$Builder;"))
    private static Random serversiderng_modifyBarteredItem(Random random) {
        return ServerSideRNG.getRngContext(RNGHandler.RNGTypes.BARTER)
            .map(Supplier::get)
            .map(Random::new)
            .orElse(random);
    }
}
