package me.voidxwalker.serversiderng.mixin.rng_verification.dragon;

import me.voidxwalker.serversiderng.RNGHandler;
import me.voidxwalker.serversiderng.ServerSideRNG;
import net.minecraft.entity.boss.dragon.EnderDragonEntity;
import net.minecraft.entity.boss.dragon.phase.StrafePlayerPhase;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Redirect;
import org.spongepowered.asm.mixin.injection.Slice;

import java.util.Random;
import java.util.function.Supplier;

@Mixin(StrafePlayerPhase.class)
public class StrafePlayerPhaseMixin {
    /**
     * Uses the from {@link ServerSideRNG#getRngContext(RNGHandler.RNGTypes)} obtained random {@code Long}, that has been generated by the {@code Verification-Server}, as a seed for the {@link RNGHandler.RNGTypes#ENDER_DRAGON_TARGET_HEIGHT} RNG.
     * @see ServerSideRNG#getRngContext(RNGHandler.RNGTypes)
     * @author Void_X_Walker
     */
    @Redirect(method = "method_6861", at = @At(value = "INVOKE", target = "Lnet/minecraft/entity/boss/dragon/EnderDragonEntity;getRandom()Ljava/util/Random;"))
    public Random serversiderng_modifyTargetHeight(EnderDragonEntity instance) {
        return ServerSideRNG
                .getRngContext(RNGHandler.RNGTypes.ENDER_DRAGON_TARGET_HEIGHT,null)
                .map(Supplier::get)
                .map(Random::new)
                .orElse(instance.getRandom());
    }
    /**
     * Uses the from {@link ServerSideRNG#getRngContext(RNGHandler.RNGTypes)} obtained random {@code Long}, that has been generated by the {@code Verification-Server}, as a seed for the {@link RNGHandler.RNGTypes#ENDER_DRAGON_PATH} RNG.
     * @see ServerSideRNG#getRngContext(RNGHandler.RNGTypes)
     * @author Void_X_Walker
     */
    @Redirect(method = "method_6860", at = @At(value = "INVOKE", target = "Lnet/minecraft/entity/boss/dragon/EnderDragonEntity;getRandom()Ljava/util/Random;"),
            slice = @Slice(
                    from = @At(value = "INVOKE", target = "Lnet/minecraft/entity/boss/dragon/EnderDragonEntity;getNearestPathNodeIndex()I"),
                    to = @At(value = "INVOKE", target = "Lnet/minecraft/entity/boss/dragon/EnderDragonEntity;findPath(IILnet/minecraft/entity/ai/pathing/PathNode;)Lnet/minecraft/entity/ai/pathing/Path;")
            )
    )
    public Random serversiderng_modifyDragonPath(EnderDragonEntity instance) {
        return ServerSideRNG
                .getRngContext(RNGHandler.RNGTypes.ENDER_DRAGON_PATH)
                .map(Supplier::get)
                .map(Random::new)
                .orElse(instance.getRandom());
    }
}
