name: "test"

on:
  pull_request:
    branches:
      - "main"
      - "master"
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build artifacts
        run: ./gradlew build
